# Generated by Django 5.2.6 on 2025-10-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alfa', '0003_alter_membro_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_fotos/'),
        ),
    ]
