# Generated by Django 5.2.6 on 2025-10-02 20:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alfa', '0006_ong_cargo_fotopostagem_oferta_distribuicaooferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='cadastrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros_cadastrados', to='app_alfa.admin'),
        ),
        migrations.AddField(
            model_name='membro',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='data_batismo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='igreja_origem',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='membro',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='dados_completos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('falecido', 'Falecido'), ('afastado', 'Afastado')], default='ativo', max_length=10),
        ),
        migrations.CreateModel(
            name='DocumentoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cartao_membro', 'Cartão de Membro'), ('transferencia', 'Transferência de Igreja'), ('registro', 'Registro de Membro')], max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos_membros/')),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='app_alfa.admin')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_alfa.membro')),
            ],
        ),
    ]
