# Generated by Django 5.2.6 on 2025-10-02 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alfa', '0007_membro_cadastrado_por_membro_cpf_membro_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='oferta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
