# Generated by Django 5.2.6 on 2025-11-01 22:36

import app_alfa.models
import app_alfa.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('pode_registrar_dizimos', models.BooleanField(default=False, help_text='Pode registrar dízimos')),
                ('pode_registrar_ofertas', models.BooleanField(default=False, help_text='Pode registrar ofertas')),
                ('pode_gerenciar_membros', models.BooleanField(default=False, help_text='Pode gerenciar membros')),
                ('pode_gerenciar_eventos', models.BooleanField(default=False, help_text='Pode gerenciar eventos')),
                ('pode_gerenciar_financas', models.BooleanField(default=False, help_text='Pode gerenciar finanças')),
                ('pode_gerenciar_cargos', models.BooleanField(default=False, help_text='Pode gerenciar cargos')),
                ('pode_gerenciar_documentos', models.BooleanField(default=False, help_text='Pode gerenciar documentos')),
                ('pode_visualizar_relatorios', models.BooleanField(default=False, help_text='Pode visualizar relatórios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='eventos_fotos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('nome', models.CharField(help_text='Nome completo do administrador', max_length=100)),
                ('email', models.EmailField(help_text='Email válido', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), app_alfa.validators.validate_email_domain])),
                ('telefone', models.CharField(blank=True, help_text='Telefone com DDD (10 ou 11 dígitos)', max_length=15, null=True, validators=[app_alfa.validators.validate_phone])),
                ('senha', models.CharField(help_text='Senha deve ter pelo menos 6 caracteres, conter letras e números', max_length=128, validators=[app_alfa.models.validate_password_strength])),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=True, help_text='Indica se é administrador do sistema')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admins', to='app_alfa.cargo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FotoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='eventos_fotos/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app_alfa.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('nome', models.CharField(help_text='Nome completo do membro', max_length=200)),
                ('cpf', models.CharField(blank=True, help_text='CPF (opcional)', max_length=14, null=True)),
                ('rg', models.CharField(blank=True, help_text='RG (opcional)', max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento (opcional)', null=True)),
                ('telefone', models.CharField(blank=True, help_text='Telefone (opcional)', max_length=15, null=True)),
                ('email', models.EmailField(help_text='Email válido', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo', null=True)),
                ('senha', models.CharField(blank=True, help_text='Senha para acesso ao sistema. Deve ter pelo menos 6 caracteres, conter letras e números', max_length=128, null=True, validators=[app_alfa.models.validate_password_strength])),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('dados_completos', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='membros_fotos/')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('falecido', 'Falecido'), ('afastado', 'Afastado')], default='ativo', max_length=10)),
                ('data_batismo', models.DateField(blank=True, null=True)),
                ('igreja_origem', models.CharField(blank=True, max_length=200, null=True)),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membros_cadastrados', to='app_alfa.admin')),
                ('cargo', models.ForeignKey(blank=True, help_text='Cargo do membro na igreja', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='app_alfa.cargo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('comentario', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app_alfa.evento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_eventos', to='app_alfa.membro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cartao_membro', 'Cartão de Membro'), ('transferencia', 'Transferência de Igreja'), ('registro', 'Registro de Membro')], max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos_membros/')),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='app_alfa.admin')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_alfa.membro')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='app_alfa.grupo')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='app_alfa.membro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('is_publico', models.BooleanField(default=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas_registradas', to='app_alfa.admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistribuicaoOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destino', models.CharField(max_length=200)),
                ('meio_envio', models.CharField(blank=True, max_length=100, null=True)),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes_ofertas/')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes', to='app_alfa.oferta')),
                ('ong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes', to='app_alfa.ong')),
            ],
        ),
        migrations.CreateModel(
            name='FotoPostagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='postagens_fotos/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app_alfa.postagem')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('categoria', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_registradas', to='app_alfa.admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('data_transferencia', models.DateField()),
                ('motivo', models.TextField(blank=True)),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_geradas', to='app_alfa.admin')),
                ('igreja_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='app_alfa.igreja')),
                ('igreja_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origem', to='app_alfa.igreja')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alfa.membro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('username', models.CharField(help_text='Nome de usuário único', max_length=150, unique=True)),
                ('email', models.EmailField(help_text='Email válido', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), app_alfa.validators.validate_email_domain])),
                ('telefone', models.CharField(blank=True, help_text='Telefone com DDD (10 ou 11 dígitos)', max_length=15, null=True, validators=[app_alfa.validators.validate_phone])),
                ('senha', models.CharField(help_text='Senha deve ter pelo menos 6 caracteres, conter letras e números', max_length=128, validators=[app_alfa.models.validate_password_strength])),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=True, help_text='Indica se é staff/colaborador')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='app_alfa.cargo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='postagem',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='app_alfa.usuario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app_alfa.usuario'),
        ),
        migrations.CreateModel(
            name='EventoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('confirmado', models.BooleanField(default=False)),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='app_alfa.evento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_eventos', to='app_alfa.membro')),
            ],
            options={
                'unique_together': {('evento', 'membro')},
            },
        ),
    ]
