# Generated by Django 5.2.6 on 2025-10-19 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('comentario', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app_alfa.evento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_eventos', to='app_alfa.membro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('confirmado', models.BooleanField(default=False)),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='app_alfa.evento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_eventos', to='app_alfa.membro')),
            ],
            options={
                'unique_together': {('evento', 'membro')},
            },
        ),
    ]
