# Generated by Django 4.2.7 on 2025-09-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alfa', '0002_igreja_postagem_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('falecido', 'Falecido')], default='ativo', max_length=10),
        ),
    ]
