# Generated by Django 5.2.6 on 2025-10-22 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alfa', '0002_eventocomentario_eventopresenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='cargo',
            field=models.ForeignKey(blank=True, help_text='Cargo do membro na igreja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='app_alfa.cargo'),
        ),
    ]
