# Generated by Django 5.2.6 on 2025-10-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alfa', '0002_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='pode_fazer_postagens',
            field=models.BooleanField(default=False, help_text='Pode criar postagens'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pode_registrar_dizimos',
            field=models.BooleanField(default=False, help_text='Pode registrar dízimos'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pode_registrar_ofertas',
            field=models.BooleanField(default=False, help_text='Pode registrar ofertas'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='app_alfa.cargo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='app_alfa.cargo'),
        ),
    ]
