# Generated by Django 5.2.6 on 2025-10-16 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Alfa', '0003_cargo_pode_fazer_postagens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app_Alfa.usuario')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app_Alfa.evento')),
                ('postagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app_Alfa.postagem')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('evento__isnull', False), ('postagem__isnull', False), _connector='OR'), name='comentario_deve_ter_evento_ou_postagem')],
            },
        ),
    ]
