# Generated by Django 5.2.6 on 2025-11-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Alfa', '0004_comentario'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transferencia',
            constraint=models.CheckConstraint(condition=models.Q(('igreja_origem', models.F('igreja_destino')), _negated=True), name='igreja_origem_diferente_destino'),
        ),
    ]
