# Generated by Django 5.2.6 on 2025-10-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alfa', '0004_evento_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fotos',
        ),
        migrations.AddField(
            model_name='evento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_fotos/'),
        ),
        migrations.CreateModel(
            name='FotoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='eventos_fotos/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app_alfa.evento')),
            ],
        ),
    ]
