# Generated by Django 5.2.6 on 2025-10-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_alfa', '0008_make_fields_required'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Remover a coluna data_criacao e manter apenas created_at
            CREATE TABLE app_alfa_cargo_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                nome varchar(100) NOT NULL UNIQUE,
                descricao TEXT,
                pode_registrar_dizimos bool NOT NULL,
                pode_registrar_ofertas bool NOT NULL,
                pode_gerenciar_membros bool NOT NULL,
                pode_gerenciar_eventos bool NOT NULL,
                pode_gerenciar_financas bool NOT NULL,
                pode_gerenciar_cargos bool NOT NULL,
                pode_gerenciar_documentos bool NOT NULL,
                pode_visualizar_relatorios bool NOT NULL,
                criado_por_id bigint,
                created_at datetime NOT NULL,
                updated_at datetime NOT NULL,
                deleted_at datetime,
                is_active bool NOT NULL
            );
            
            -- Copiar dados existentes (se houver)
            INSERT INTO app_alfa_cargo_new 
            SELECT id, nome, descricao, pode_registrar_dizimos, pode_registrar_ofertas, 
                   pode_gerenciar_membros, pode_gerenciar_eventos, pode_gerenciar_financas,
                   pode_gerenciar_cargos, pode_gerenciar_documentos, pode_visualizar_relatorios,
                   criado_por_id, created_at, updated_at, deleted_at, is_active
            FROM app_alfa_cargo;
            
            -- Remover tabela antiga e renomear nova
            DROP TABLE app_alfa_cargo;
            ALTER TABLE app_alfa_cargo_new RENAME TO app_alfa_cargo;
            """,
            reverse_sql="-- Não há como reverter esta operação"
        ),
    ]
