# Generated by Django 5.2.6 on 2025-10-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_alfa', '0009_fix_cargo_columns'),
    ]

    operations = [
        migrations.RunSQL(
            # Remover campos antigos da tabela Usuario
            """
            CREATE TABLE app_alfa_usuario_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username VARCHAR(150) NOT NULL UNIQUE,
                email VARCHAR(254) NOT NULL UNIQUE,
                telefone VARCHAR(15),
                senha VARCHAR(128) NOT NULL,
                last_login DATETIME,
                cargo_id BIGINT,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                deleted_at DATETIME,
                is_active BOOLEAN NOT NULL,
                is_staff BOOLEAN NOT NULL
            );
            
            INSERT INTO app_alfa_usuario_new 
            (id, username, email, telefone, senha, last_login, cargo_id, created_at, updated_at, deleted_at, is_active, is_staff)
            SELECT 
                id, username, email, telefone, senha, last_login, cargo_id, created_at, updated_at, deleted_at, is_active, is_staff
            FROM app_alfa_usuario;
            
            DROP TABLE app_alfa_usuario;
            ALTER TABLE app_alfa_usuario_new RENAME TO app_alfa_usuario;
            """,
            reverse_sql=""
        ),
    ]
